### PR TITLE
virttest.utils_net: Use correct module for wait_for

### PR DESCRIPTION
**Pull request by ldoktor**
This is a simple fix for:

```
16:10:23 ERROR| Traceback (most recent call last):
16:10:23 ERROR|   File "/home/virt-test/virttest/standalone_test.py", line 220, in run_once
16:10:23 ERROR|     run_func(self, params, env)
16:10:23 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", line 141, in new_fn
16:10:23 ERROR|     return fn(*args, **kwargs)
16:10:23 ERROR|   File "/home/virt-test/test-providers.d/downloads/io-github-autotest-qemu/generic/tests/boot.py", line 25, in run
16:10:23 ERROR|     session = vm.wait_for_login(timeout=timeout)
16:10:23 ERROR|   File "/home/virt-test/virttest/virt_vm.py", line 1022, in wait_for_login
16:10:23 ERROR|     username, password)
16:10:23 ERROR|   File "/usr/lib/python2.7/site-packages/autotest/client/shared/error.py", line 141, in new_fn
16:10:23 ERROR|     return fn(*args, **kwargs)
16:10:23 ERROR|   File "/home/virt-test/virttest/virt_vm.py", line 927, in login
16:10:23 ERROR|     address = self.get_address(nic_index)
16:10:23 ERROR|   File "/home/virt-test/virttest/virt_vm.py", line 680, in get_address
16:10:23 ERROR|     if not utils_net.verify_ip_address_ownership(arp_ip, macs):
16:10:23 ERROR|   File "/home/virt-test/virttest/utils_net.py", line 2668, in verify_ip_address_ownership
16:10:23 ERROR|     ret = utils.wait_for(lambda: __arping(regex, arping_cmd, ip),
16:10:23 ERROR| AttributeError: 'module' object has no attribute 'wait_for'
```

bug introduced in 6e6e88de12f05234a5ea548be36c23ba2ad55ee9

@xutian would you please take a look at it?

### CODE REVIEW

**Comment by ldoktor** [comment]
Well it seems like there is more. I'm trying it on ARM and with the 6e6e88d it still reports no matches (unattended_install test). I'll investigate this further tomorrow. Anyway the fix is valid and should be applied, more might come later...

**Comment by xutian** [comment]
hi @ldoktor 
not reproduced in my tree, and double check upstream master tree, it looks we have function wait_for in utils module. 
https://github.com/autotest/autotest/blob/master/client/shared/utils.py
so, please check you used a clean tree.

Thanks,
Xu

**Comment by xutian** [comment]
Double check utils_misc module,  it has same function in utils module, so this fix is ok for me.

Thanks,
Xu

**Comment by ypu** [comment]
LGTM

Acked-by: Yiqiao Pu <ypu@redhat.com>

**Comment by ypu** [comment]
Thanks @ldoktor and @xutian will merge it.

**Comment by ldoktor** [comment]
Thanks, I'm using the latest RPM, which is 0.16.0.3 which doesn't have it...
