### ISSUE TITLE
Spawn(object) causes uninitialized Tail thread filure

### ISSUE THREAD

**Issue by ldoktor** [autotest/virt-test#640]
Hi guys,

today I observed failures when executing a test twice by executing `autotest-local` twice.

It fails with:

<pre>
13:21:35 DEBUG|     used_cpus = 2
13:21:35 DEBUG|     used_mem = 512
13:21:35 DEBUG|     username = root
13:21:35 DEBUG|     vcpu_thread_pattern = thread_id=(\d+)
13:21:35 DEBUG|     vfd_size = 1440k
13:21:35 DEBUG|     vga = std
13:21:35 DEBUG|     virt_install_wait_time = 300
13:21:35 DEBUG|     virt_test_type = qemu libvirt
13:21:35 DEBUG|     vm_arch_name = x86_64
13:21:35 DEBUG|     vm_type = qemu
13:21:35 DEBUG|     vms = virt-tests-vm1
13:21:35 DEBUG|     vnc_autoport = yes
13:22:03 ERROR| Test failed: AttributeError: 'Tail' object has no attribute 'lock_server_running_filename'
13:22:03 ERROR| 'Expect' object has no attribute 'lock_server_running_filename'
13:22:03 ERROR| Exception raised during postprocessing: 'Expect' object has no attribute 'lock_server_running_filename'
13:22:03 ERROR| Exception AttributeError: "'Tail' object has no attribute 'reader_fds'" in <bound method Tail.__del__ of <virttest.aexpect.Tail object at 0x353d550>> ignored
13:22:03 ERROR| Exception AttributeError: "'Expect' object has no attribute 'reader_fds'" in <bound method Expect.__del__ of <virttest.aexpect.Expect object at 0x353d710>> ignored
13:22:03 ERROR| Exception AttributeError: "'Tail' object has no attribute 'reader_fds'" in <bound method Tail.__del__ of <virttest.aexpect.Tail object at 0x3649490>> ignored
13:22:03 ERROR| Exception AttributeError: "'ShellSession' object has no attribute 'reader_fds'" in <bound method ShellSession.__del__ of <virttest.aexpect.ShellSession object at 0x3649bd0>> ignored
13:22:03 ERROR| Exception AttributeError: "'ShellSession' object has no attribute 'reader_fds'" in <bound method ShellSession.__del__ of <virttest.aexpect.ShellSession object at 0x3649b90>> ignored
13:22:03 ERROR| Exception escaping from test:
Traceback (most recent call last):
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 426, in _exec
    _call_test_function(self.execute, *p_args, **p_dargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 853, in _call_test_function
    raise error.UnhandledTestFail(e)
UnhandledTestFail: Unhandled AttributeError: 'Tail' object has no attribute 'lock_server_running_filename'    [context: preprocessing]
Traceback (most recent call last):
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 846, in _call_test_function
    return func(*args, **dargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 299, in execute
    postprocess_profiled_run, args, dargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 216, in _call_run_once
    *args, **dargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/test.py", line 322, in run_once_profiling
    self.run_once(*args, **dargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/tests/virt/virt.py", line 128, in run_once
    params = env_process.preprocess(self, params, env)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/shared/error.py", line 138, in new_fn
    return fn(*args, **kwargs)
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/tests/virt/virttest/env_process.py", line 335, in preprocess
    if "tcpdump" in env and not env["tcpdump"].is_alive():
  File "/home/medic/Work/Projekty/autotest/autotest-ldoktor/client/tests/virt/virttest/aexpect.py", line 584, in is_alive
    return _locked(self.lock_server_running_filename)
AttributeError: 'Tail' object has no attribute 'lock_server_running_filename'
</pre>

I tried to hunt it down and it was caused by df3f719d1aed5a21f74e851053f74fddbee8c91a and it's related to `env.save()`. When an old style class is pickled, it stores the state by `__getstate__()` and restores it. But when the class is object, it's stored differently:

<pre>
# Store
def _reduce_ex(self, proto):
    assert proto &lt 2
    for base in self.__class__.__mro__:
        if hasattr(base, '__flags__') and not base.__flags__ & _HEAPTYPE:
            break
    else:
        base = object # not really reachable
    if base is object:
        state = None
    else:
        if base is self.__class__:
            raise TypeError, "can't pickle %s objects" % base.__name__
        state = base(self)
    args = (self.__class__, base, state)
    try:
...

# Restore
def _reconstructor(cls, base, state):
    if base is object:
        obj = object.__new__(cls)
    else:
        obj = base.__new__(cls, state)
        if base.__init__ != object.__init__:
            base.__init__(obj, state)
    return obj
</pre>

I tried to solve this issue, but my python knowledge is insufficient in this area. Please take a look on it or temporarily rip of this patch.
